export type TRotmgDungeon = {
  name: string;
  difficulty: number;
  height: number;
  width: number;
  imageInd: number;
};

export const ROTMG_REALM_DUNGEONS = [
  {
    name: "Pirate Cave",
    difficulty: 1,
    src: "https://i.imgur.com/OqzVQuc.png",
  },
  {
    name: "Forest Maze",
    difficulty: 1,
    src: "https://i.imgur.com/m0AO506.png",
  },
  {
    name: "Spider Den",
    difficulty: 1.5,
    src: "https://i.imgur.com/up93OlG.png",
  },
  {
    name: "Forbidden Jungle",
    difficulty: 1.5,
    src: "https://i.imgur.com/beQHm21.png",
  },
  {
    name: "The Hive",
    difficulty: 2,
    src: "https://i.imgur.com/6WiS9zQ.png",
  },
  {
    name: "Snake Pit",
    difficulty: 2,
    src: "https://i.imgur.com/Mhtm0aR.png",
  },
  {
    name: "Sprite World",
    difficulty: 2.5,
    src: "https://i.imgur.com/K0dJRrF.png",
  },
  {
    name: "Cave of a Thousand Treasures",
    difficulty: 2.5,
    src: "https://i.imgur.com/6lgodhZ.png",
  },
  {
    name: "Ancient Ruins",
    difficulty: 3,
    src: "https://i.imgur.com/4gtP9OQ.png",
  },
  {
    name: "Magic Woods",
    difficulty: 3,
    src: "https://i.imgur.com/nmLtcBD.png",
  },
  {
    name: "Candyland Hunting Grounds",
    difficulty: 3.5,
    src: "https://i.imgur.com/BKoSv6j.png",
  },
  {
    name: "Undead Lair",
    difficulty: 3.5,
    src: "https://i.imgur.com/pR8Dgth.png",
  },
  {
    name: "Puppet Master's Theatre",
    difficulty: 4,
    src: "https://i.imgur.com/6diBou4.png",
  },
  {
    name: "Toxic Sewers",
    difficulty: 4,
    src: "https://i.imgur.com/4Iv5apz.png",
  },
  {
    name: "Cursed Library",
    difficulty: 4,
    src: "https://i.imgur.com/9nQ7nSz.gif",
  },
  {
    name: "Mad Lab",
    difficulty: 4,
    src: "https://i.imgur.com/x6dyxMp.gif",
  },
  {
    name: "Abyss of Demons",
    difficulty: 4,
    src: "https://i.imgur.com/wId2zPS.png",
  },
  {
    name: "Manor of the Immortals",
    difficulty: 4,
    src: "https://i.imgur.com/paEB8Qu.png",
  },
  {
    name: "Haunted Cemetery",
    difficulty: 4.5,
    src: "https://i.imgur.com/VB6hMsm.gif",
  },
  {
    name: "The Machine",
    difficulty: 4.5,
    src: "https://i.imgur.com/Yhd1MCq.png",
  },
  {
    name: "Davy Jones Locker",
    difficulty: 5,
    src: "https://i.imgur.com/Hqmoe5U.gif",
  },
  {
    name: "Ice Cave",
    difficulty: 5,
    src: "https://i.imgur.com/PCB2ged.png",
  },
  {
    name: "Ocean Trench",
    difficulty: 5,
    src: "https://i.imgur.com/9GR3Ypw.png",
  },
  {
    name: "The Crawling Depths",
    difficulty: 5.5,
    src: "https://i.imgur.com/V1rfmTa.gif",
  },
  {
    name: "Woodland Labyrinth",
    difficulty: 5.5,
    src: "https://i.imgur.com/jyKYlZg.gif",
  },
  {
    name: "Deadwater Docks",
    difficulty: 5.5,
    src: "https://i.imgur.com/baXW11C.png",
  },
  {
    name: "Puppet Master's Encore",
    difficulty: 5.5,
    src: "https://i.imgur.com/UhdCm8R.png",
  },
  {
    name: "Cnidarian Reef",
    difficulty: 5.5,
    src: "https://i.imgur.com/pXFqErd.png",
  },
  {
    name: "Sulfurous Wetlands",
    difficulty: 6,
    src: "https://i.imgur.com/88fMxeA.png",
  },
  {
    name: "Parasite Chambers",
    difficulty: 6,
    src: "https://i.imgur.com/O43mDnf.gif",
  },
  {
    name: "Mountain Temple",
    difficulty: 6,
    src: "https://i.imgur.com/fGgckZI.png",
  },
  {
    name: "Lair of Draconis",
    difficulty: 6,
    src: "https://i.imgur.com/QjX8g5O.png",
  },
  {
    name: "Tomb of the Ancients",
    difficulty: 6,
    src: "https://i.imgur.com/E6a3nHx.png",
  },
  {
    name: "The Third Dimension",
    difficulty: 6,
    src: "https://i.imgur.com/X3j3GrM.png",
  },
  {
    name: "Lair of Shaitan",
    difficulty: 6,
    src: "https://i.imgur.com/px7FwlI.png",
  },
  {
    name: "Secluded Thicket",
    difficulty: 6.5,
    src: "https://i.imgur.com/IeOHusO.png",
  },
  {
    name: "High Tech Terror",
    difficulty: 6.5,
    src: "https://i.imgur.com/2SwppYx.png",
  },
  {
    name: "Moonlight Village",
    difficulty: 9,
    src: "https://i.imgur.com/CHqjDCE.png",
  },
];

export const ROTMG_EVENT_DUNGEONS = [
  {
    name: "Beachzone",
    difficulty: 0,
    src: "https://i.imgur.com/Ns31EKU.png",
  },
  {
    name: "The Tavern",
    difficulty: 5.5,
    src: "https://i.imgur.com/DwtjA17.png",
  },
  {
    name: "The Nest",
    difficulty: 7,
    src: "https://i.imgur.com/4oOmRd4.png",
  },
  {
    name: "Cultist Hideout",
    difficulty: 7,
    src: "https://i.imgur.com/Xa9mjsG.png",
  },
  {
    name: "Fungal Cavern",
    difficulty: 7.5,
    src: "https://i.imgur.com/CLzxdEM.png",
  },
  {
    name: "Crystal Cavern",
    difficulty: 7.5,
    src: "https://i.imgur.com/Cd6RD9G.png",
  },
  {
    name: "Spectral Penitentiary",
    difficulty: 8,
    src: "https://i.imgur.com/o9yNqBT.png",
  },
  {
    name: "Kogbold Steamworks",
    difficulty: 8,
    src: "https://i.imgur.com/dohicSR.png",
  },
  {
    name: "Lost Halls",
    difficulty: 8,
    src: "https://i.imgur.com/DwuQOQQ.png",
  },
  {
    name: "The Void",
    difficulty: 8.5,
    src: "https://i.imgur.com/ijlxjJM.png",
  },
  {
    name: "Advanced Kogbold Steamworks",
    difficulty: 10,
    src: "https://i.imgur.com/4V6j3wj.png",
  },
  {
    name: "Advanced Nest",
    difficulty: 10,
    src: "https://i.imgur.com/ZZssHia.png",
  },
  {
    name: "The Shatters",
    difficulty: 10,
    src: "https://i.imgur.com/yA4tlry.png",
  },
];

export const ROTMG_WORMHOLE_DUNGEONS = [
  {
    name: "Malogia",
    difficulty: 5,
    src: "https://i.imgur.com/RNrgJ5t.png",
  },
  {
    name: "Untaris",
    difficulty: 5,
    src: "https://i.imgur.com/WlZyR9Z.png",
  },
  {
    name: "Katalund",
    difficulty: 5,
    src: "https://i.imgur.com/EvOyU7Z.png",
  },
  {
    name: "Forax",
    difficulty: 5,
    src: "https://i.imgur.com/KyAxJXQ.png",
  },
];

export const ROTMG_ORYX_DUNGEONS = [
  {
    name: "Court of Oryx",
    difficulty: 3.5,
    src: "https://i.imgur.com/AUfvKkf.png",
  },
  {
    name: "Oryx's Chamber",
    difficulty: 4.5,
    src: "https://i.imgur.com/dLVOZiv.png",
  },
  {
    name: "Wine Cellar",
    difficulty: 6,
    src: "https://i.imgur.com/ozNWFFN.png",
  },
  {
    name: "Oryx's Sanctuary",
    difficulty: 9.5,
    src: "https://i.imgur.com/JGnMCv2.png",
  },
];

export const ROTMG_HEROIC_DUNGEONS = [
  {
    name: "Heroic Undead Lair",
    difficulty: 5,
    src: "https://i.imgur.com/G4CcZWp.png",
  },
  {
    name: "Heroic Abyss of Demons",
    difficulty: 5,
    src: "https://i.imgur.com/qpULefS.png",
  },
];

export const ROTMG_SPECIAL_DUNGEONS = [
  {
    name: "Rainbow Road",
    difficulty: 0,
    src: "https://i.imgur.com/MDVaDzN.png",
  },
  {
    name: "Santa's Workshop",
    difficulty: 0,
    src: "https://i.imgur.com/oX3aVA2.png",
  },
  {
    name: "Ice Tomb",
    difficulty: 6,
    src: "https://i.imgur.com/zhWVACc.png",
  },
  {
    name: "Battle for the Nexus",
    difficulty: 5,
    src: "https://i.imgur.com/zyCjq2l.png",
  },
  {
    name: "Belladonna's Garden",
    difficulty: 5.5,
    src: "https://i.imgur.com/iIG3NIj.png",
  },
  {
    name: "Queen Bunny Chamber",
    difficulty: 5.5,
    src: "https://i.imgur.com/li7XrWv.png",
  },
  {
    name: "Mad God Mayhem",
    difficulty: 6,
    src: "https://i.imgur.com/U9HeRQ4.png",
  },
  {
    name: "Hidden Interregnum",
    difficulty: 7,
    src: "https://i.imgur.com/voULRFc.png",
  },
  {
    name: "White Snake Invasion I",
    difficulty: 6.5,
    src: "https://i.imgur.com/SW85m6U.png",
  },
  {
    name: "White Snake Invasion II",
    difficulty: 7.5,
    src: "https://i.imgur.com/F1WWPv7.png",
  },
  {
    name: "White Snake Invasion III",
    difficulty: 8.5,
    src: "https://i.imgur.com/aicgQzn.png",
  },
];

export const ROTMG_COMBINED_DUNGEONS = [
  ...ROTMG_REALM_DUNGEONS,
  ...ROTMG_EVENT_DUNGEONS,
  ...ROTMG_WORMHOLE_DUNGEONS,
  ...ROTMG_ORYX_DUNGEONS,
  ...ROTMG_HEROIC_DUNGEONS,
  ...ROTMG_SPECIAL_DUNGEONS,
];

export const ROTMG_DUNGEON_FAME_BONUSES = [
  {
    name: "First Steps",
    dungeonList: [
      "Pirate Cave",
      "Forest Maze",
      "Forbidden Jungle",
      "Spider Den",
      "The Hive",
    ],
    fame: 100,
    bonusPercent: 2.5,
  },
  {
    name: "King of the Mountains",
    dungeonList: [
      "Snake Pit",
      "Sprite World",
      "Abyss of Demons",
      "Toxic Sewers",
      "Mad Lab",
      "Magic Woods",
      "Puppet Master's Theatre",
      "Haunted Cemetery",
      "Cursed Library",
      "Ancient Ruins",
      "Sulfurous Wetlands",
      "Spectral Penitentiary",
    ],
    fame: 1000,
    bonusPercent: 5,
  },
  {
    name: "Epic Battles",
    dungeonList: [
      "Deadwater Docks",
      "Woodland Labyrinth",
      "The Crawling Depths",
      "The Nest",
      "Secluded Thicket",
    ],
    fame: 2000,
    bonusPercent: 7.5,
  },
  {
    name: "Far Out",
    dungeonList: ["Malogia", "Untaris", "Forax", "Katalund"],
    fame: 2000,
    bonusPercent: 5,
  },
  {
    name: "Tunnel Rat",
    dungeonList: [
      "Pirate Cave",
      "Forbidden Jungle",
      "Spider Den",
      "Snake Pit",
      "Undead Lair",
      "Abyss of Demons",
      "Manor of the Immortals",
      "Ocean Trench",
      "Tomb of the Ancients",
      "Oryx's Chamber",
      "Wine Cellar",
    ],
    fame: 3000,
    bonusPercent: 7.5,
  },
  {
    name: "Explosive Journey",
    dungeonList: [
      "Davy Jones Locker",
      "Mad Lab",
      "Candyland Hunting Grounds",
      "Haunted Cemetery",
      "Cave of a Thousand Treasures",
      "Lair of Draconis",
      "Deadwater Docks",
      "Woodland Labyrinth",
      "The Crawling Depths",
      "The Shatters",
      "Lair of Shaitan",
      "Puppet Master's Theatre",
      "Ice Cave",
    ],
    fame: 3000,
    bonusPercent: 7.5,
  },
  {
    name: "Enemy of the Court",
    dungeonList: [
      "Lair of Shaitan",
      "Puppet Master's Encore",
      "Cnidarian Reef",
      "Secluded Thicket",
      "High Tech Terror",
    ],
    fame: 3000,
    bonusPercent: 7.5,
  },
  {
    name: "Conqueror of the Realm",
    dungeonList: [
      "Davy Jones Locker",
      "Ice Cave",
      "Lair of Draconis",
      "Mountain Temple",
      "The Third Dimension",
      "Ocean Trench",
      "Tomb of the Ancients",
      "The Shatters",
      "The Nest",
      "Fungal Cavern",
      "Crystal Cavern",
      "Lost Halls",
      "Kogbold Steamworks",
    ],
    fame: 4000,
    bonusPercent: 10,
  },
  {
    name: "Travel of the Decade",
    dungeonList: [
      "Puppet Master's Encore",
      "The Hive",
      "Toxic Sewers",
      "Mountain Temple",
      "The Third Dimension",
      "The Nest",
      "Lost Halls",
      "Cultist Hideout",
      "The Void",
      "Cnidarian Reef",
      "Parasite Chambers",
      "Magic Woods",
      "Secluded Thicket",
      "Cursed Library",
      "Oryx's Sanctuary",
      "Ancient Ruins",
      "High Tech Terror",
      "Sulfurous Wetlands",
      "Spectral Penitentiary",
    ],
    fame: 5000,
    bonusPercent: 10,
  },
  {
    name: "Hero of the Nexus",
    dungeonList: [
      "Pirate Cave",
      "Forest Maze",
      "Spider Den",
      "Snake Pit",
      "Forbidden Jungle",
      "The Hive",
      "Ancient Ruins",
      "Magic Woods",
      "Sprite World",
      "Candyland Hunting Grounds",
      "Cave of a Thousand Treasures",
      "Undead Lair",
      "Abyss of Demons",
      "Manor of the Immortals",
      "Puppet Master's Theatre",
      "Toxic Sewers",
      "Cursed Library",
      "Haunted Cemetery",
      "Mad Lab",
      "Parasite Chambers",
      "Davy Jones Locker",
      "Mountain Temple",
      "The Third Dimension",
      "Lair of Draconis",
      "Deadwater Docks",
      "Woodland Labyrinth",
      "The Crawling Depths",
      "Ocean Trench",
      "Ice Cave",
      "Tomb of the Ancients",
      "Fungal Cavern",
      "Crystal Cavern",
      "The Nest",
      "The Shatters",
      "Lost Halls",
      "Cultist Hideout",
      "The Void",
      "Sulfurous Wetlands",
      "Kogbold Steamworks",
      "Oryx's Chamber",
      "Lair of Shaitan",
      "Puppet Master's Encore",
      "Cnidarian Reef",
      "Secluded Thicket",
      "High Tech Terror",
      "Wine Cellar",
      "Oryx's Sanctuary",
      "Spectral Penitentiary",
    ],
    fame: 5000,
    bonusPercent: 12.5,
  },
  {
    name: "Season's Beatins",
    dungeonList: [
      "Belladonna's Garden",
      "Ice Tomb",
      "Mad God Mayhem",
      "Battle for the Nexus",
      "Santa's Workshop",
      "The Machine",
      "Malogia",
      "Untaris",
      "Forax",
      "Katalund",
      "Rainbow Road",
      "Beachzone",
    ],
    fame: 5000,
    bonusPercent: 12.5,
  },
  {
    name: "Realm of the Mad God",
    dungeonList: [
      "Pirate Cave",
      "Forest Maze",
      "Spider Den",
      "Snake Pit",
      "Forbidden Jungle",
      "The Hive",
      "Ancient Ruins",
      "Magic Woods",
      "Sprite World",
      "Candyland Hunting Grounds",
      "Cave of a Thousand Treasures",
      "Undead Lair",
      "Abyss of Demons",
      "Manor of the Immortals",
      "Puppet Master's Theatre",
      "Toxic Sewers",
      "Cursed Library",
      "Haunted Cemetery",
      "Mad Lab",
      "Parasite Chambers",
      "Davy Jones Locker",
      "Mountain Temple",
      "The Third Dimension",
      "Lair of Draconis",
      "Deadwater Docks",
      "Woodland Labyrinth",
      "The Crawling Depths",
      "Ocean Trench",
      "Ice Cave",
      "Tomb of the Ancients",
      "Fungal Cavern",
      "Crystal Cavern",
      "The Nest",
      "The Shatters",
      "Lost Halls",
      "Cultist Hideout",
      "The Void",
      "Sulfurous Wetlands",
      "Kogbold Steamworks",
      "Oryx's Chamber",
      "Lair of Shaitan",
      "Puppet Master's Encore",
      "Cnidarian Reef",
      "Secluded Thicket",
      "High Tech Terror",
      "Wine Cellar",
      "Oryx's Sanctuary",
      "Belladonna's Garden",
      "Ice Tomb",
      "Mad God Mayhem",
      "Battle for the Nexus",
      "Santa's Workshop",
      "The Machine",
      "Malogia",
      "Untaris",
      "Forax",
      "Katalund",
      "Rainbow Road",
      "Beachzone",
      "Spectral Penitentiary",
    ],
    fame: 10000,
    bonusPercent: 25,
  },
];
